### ISSUE TITLE
你好，我按照您的说明运行代码，但是出现如下报错

### ISSUE THREAD

**Issue by Wei-Wu233** [Double-zh/ByteTrack#5]
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from yolox.core import Trainer, launch
  File "D:\github_rar\ByteTrack_zz\yolox\__init__.py", line 4, in <module>
    from .utils import configure_module
  File "D:\github_rar\ByteTrack_zz\yolox\utils\__init__.py", line 15, in <module>
    from .setup_env import *
  File "D:\github_rar\ByteTrack_zz\yolox\utils\setup_env.py", line 5, in <module>
    sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages')
ValueError: list.remove(x): x not in list

**Comment by xiaoxiaolu1111** [comment]
将train.py和setup_env.py中的 sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages')注释掉即可
